# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test_and_deploy:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: circleci/node:latest
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Install"
          command: "npm install"
      - run:
          name: "Run build"
          command: "npm run build"
      - aws-ecr/build-and-push-image:
        aws-access-key-id: $AWS_ID
        aws-secret-access-key: $AWS_Secret
        region: $AWS_Region
        registry-id: 451213086978.dkr.ecr.eu-central-1.amazonaws.com
        name: "Build and push Docker image to ECR"
        path: .
        tag: latest

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build_and_test:
    jobs:
      - test_and_deploy:
          context:
            - AWS